-- 创建错误日志表
CREATE TABLE `error_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `exception_type` varchar(100) DEFAULT NULL COMMENT '异常类型',
  `message` text COMMENT '异常消息',
  `stack_trace` longtext COMMENT '堆栈追踪',
  `class_name` varchar(500) DEFAULT NULL COMMENT '类名',
  `method_name` varchar(100) DEFAULT NULL COMMENT '方法名',
  `file_name` varchar(200) DEFAULT NULL COMMENT '文件名',
  `line_number` int DEFAULT NULL COMMENT '行号',
  `url` varchar(500) DEFAULT NULL COMMENT '请求URL',
  `params` text COMMENT '请求参数',
  `ip` varchar(50) DEFAULT NULL COMMENT 'IP地址',
  `user_agent` varchar(500) DEFAULT NULL COMMENT '用户代理',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `username` varchar(50) DEFAULT NULL COMMENT '用户名',
  `level` varchar(20) DEFAULT NULL COMMENT '错误级别(ERROR/WARN/FATAL)',
  `module` varchar(100) DEFAULT NULL COMMENT '模块名称',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_username` (`username`),
  KEY `idx_exception_type` (`exception_type`),
  KEY `idx_level` (`level`),
  KEY `idx_module` (`module`),
  KEY `idx_ip` (`ip`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_level_time` (`level`, `create_time`),
  KEY `idx_module_time` (`module`, `create_time`),
  KEY `idx_user_time` (`user_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='错误日志表';